version: 2.1

jobs:
  deploy_backend:
    docker:
      - image: circleci/node:latest
    resource_class: medium
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:2Mf6r10u4sI878EMHKCdVNdaOvjt5dWTwcY62fkJcyo"
      - checkout
      - run:
          name: Deploy Backend
          command: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_rsa ubuntu@13.236.248.5 \
                "cd /var/www/html/big_picture_back && \
                 sudo git pull 
               


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy_backend:
          filters:
            branches:
              only:
                - updated-develop
      - restart_pm2:
          requires:
            - deploy_backend

